version: '3.8'
services:
  fredy:
    container_name: fredy
    # build from empty build folder to reduce size of image
    build:
      context: .
      dockerfile: Dockerfile
    image: fredy/fredy
    # map existing config and database
    volumes:
      - ./conf:/conf
      - ./db:/db
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    ports:
        - 9998:9998
#        - 443:443
    environment:
      HTTPS_PORT: 443
    restart: unless-stopped
